In [7]:
import pandas as pd

In [8]:
import numpy as np

In [12]:
df = pd.read_csv(
   'car_fuel_efficiency_2026.csv')

In [13]:
df.head(2)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3

In [ ]:
1. Pandas Version

In [2]:
pd.__version__

'2.2.3'

In [ ]:
2. How many records are in the dataset?

In [6]:
df.shape

(10000, 11)

In [14]:
len(df)

10000

In [ ]:
3. How many fuel types are presented?

In [15]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [16]:
df['fuel_type'].nunique()

3

In [ ]:
4. How many columns have missing values?

In [17]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [18]:
df.isnull().any().sum()

np.int64(2)

In [ ]:
5. Maximum fuel efficiency of cars from Asia

In [19]:
df[df['origin'] == 'Asia']

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [20]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg']

2       27.5
6       26.8
8       30.9
10      26.8
15      35.4
        ...
9984    32.4
9987    29.0
9990    32.4
9994    30.1
9996    30.0
Name: fuel_efficiency_mpg, Length: 2994, dtype: float64

In [21]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

41.2

In [ ]:
6. Median value of horsepower

In [ ]:
i.Find the median value of the horsepower column in the dataset.

In [22]:
df['horsepower'].median()

254.0

In [23]:
median_hp = df['horsepower'].median()

print(median_hp)

254.0

In [ ]:
ii. Next, calculate the most frequent value of the same horsepower column.

In [24]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [25]:
most_frequent_hp = df['horsepower'].mode()[0]

print(most_frequent_hp)

252.0

In [27]:
df.mode()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,1990,USA,Gasoline,Front-wheel drive,4,2250,6,252.0,4270,18.8,30.2

In [29]:
iii. Fill missing horsepower values

SyntaxError: invalid syntax (2418797691.py, line 1)

In [30]:
most_frequent_hp = df['horsepower'].mode()[0]

In [31]:
df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

In [32]:
most_frequent_hp = df['horsepower'].mode()[0]

df['horsepower'] = df['horsepower'].fillna(most_frequent_hp)

In [34]:
df.fillna(250)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,250.0,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,250.0,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [ ]:
iv. Now, calculate the median value of horsepower once again.

In [35]:
new_median_hp = df['orsepower'].median()

print(new_median_hp)

252.0

In [36]:
print("Original median:", median_hp)
print("New median:", new_median_hp)

Original median: 254.0
New median: 252.0

In [ ]:
v. Has it changed? -- Yes, it increased

In [37]:
if new_median_hp > median_hp:
    print("Yes, it increased")
elif new_median_hp < median_hp:
    print("Yes, it decreased")
else:
    print("No")

Yes, it decreased

In [ ]:
7. sum of weights

In [ ]:
a. Select all the cars from Asia

In [50]:
asia_cars = df[df['origin'] == 'Asia']

In [51]:
asia_cars['vehicle_weight']

2       4240
6       4310
8       4230
10      4420
15      3950
        ...
9984    4610
9987    4530
9990    3630
9994    4610
9996    4370
Name: vehicle_weight, Length: 2994, dtype: int64

In [52]:
asia_cars['vehicle_weight'].sum()

np.int64(12679600)

In [53]:
df[df['origin'] == 'Asia']['vehicle_weight'].sum()

np.int64(12679600)

In [ ]:
b. Select only columns vehicle_weight and model_year

In [54]:
X = asia_cars[['vehicle_weight', 'model_year']]

In [ ]:
c. Select the first 7 values

In [55]:
X = X.head(7)

In [56]:
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [46]:
d. Get the underlying NumPy array. Let's call it X.

SyntaxError: unterminated string literal (detected at line 1) (2102248259.py, line 1)

In [57]:
X = X.values

In [58]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [ ]:
e. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [59]:
X.T @ X

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [60]:
XTX = X.T @ X

In [ ]:
f. Invert XTX.

In [61]:
XTX_inv = np.linalg.inv(XTX)

In [62]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [ ]:
g. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [63]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [65]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [ ]:
h. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [64]:
w = XTX_inv @ X.T @ y

In [66]:
w

array([0.13644777, 0.2327492 ])

In [ ]:
i. What's the sum of all the elements of the result? -- 0.369

In [67]:
w.sum()

np.float64(0.3691969690492638)